spring.application.name=CloudNest

#Authentication
spring.security.user.name=user
spring.security.user.password=1234

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/CloudNest
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

#Minio
minio.endpoint="http://localhost:9000"
minio.username="admin"
minio.password="password123"

#Metrics
management.endpoints.web.exposure.include=*

