spring.application.name=CloudNest
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

#Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/CloudNest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.open-in-view=false

#Minio
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.username=${MINIO_USERNAME:admin}
minio.password=${MINIO_PASSWORD:password123}
minio.bucket=${MINIO_BUCKET:uploads}

#Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
